config/routes.rb
Rails.application.routes.draw do
  resources :widgets, only: [:index, :create, :destroy] do
  	collection do
  	  get :all
  	end
  end

  resources :users, only: [:index, :show, :create] do
  	collection do
      get :me
  	  put :update_profile
      post :reset_password
  	end
  end

  resources :sessions, only: [:create, :destroy]

  get 'users/me/widgets' => 'widgets#all'
  post 'users/me/change_password' => 'users#change_password'
  root 'widgets#index'
end

app/models/user.rb
class User
  REDIS_KEY = "users".freeze

  class << self
    def create(params)
      email = params[:email] || params['email']

      params.each do |key, value|
        redis.hset("#{REDIS_KEY}:#{email}", key, value)
      end
    end

    def find_by_email(email)
      redis.hgetall("#{REDIS_KEY}:#{email}")
    end

    private

    def redis
      @redis ||= Redis.new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :danger, :warning

  include Authenticatable
  include ExceptionHandler
end

app/controllers/concerns/authenticatable.rb
module Authenticatable
  extend ActiveSupport::Concern

  included do
    helper_method :current_user, :user_logged_in?
  end

  def current_user
    return unless user_logged_in?

    @current_user ||= User.find_by_email(session[:user_email])
  end

  def user_logged_in?
    session[:user_email].present?
  end

  def sign_in(user)
    return if user.blank?

    session[:user_email] = user['email'] || user[:email]
  end

  def sign_out
    begin
      api_client.revoke_token(revoke_params) if current_user.present?
      session[:user_email] = nil
      flash[:info] = 'Logged out!'
    rescue => e
      flash[:danger] = e.message
    end
  end

  def api_client
  	@api_client ||= if user_logged_in?
      WidgetsAPI::V1::Client.new(
        access_token: current_user['access_token'],
        token_type: current_user['token_type'],
      )
    else
      WidgetsAPI::V1::Client.new
    end
  end

  private

  def revoke_params
    { token: current_user['access_token'] }
  end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from Faraday::ConnectionFailed, with: :no_network
    rescue_from ApiExceptions::UnauthorizedError, with: :render_422
  end

  private

  def no_network(exception)
    @exception = 'Please check your connectivity. Seems like you are not connected to internet'
    render 'layouts/no_network.html.haml', layout: 'exception_layout'
  end

  def render_422(exception)
    sign_out
    redirect_to root_path, warning: exception
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    begin
      response = api_client.authenticate(create_params)
      User.create(redis_params(response))
      sign_in({ 'email': permitted_params[:username] })
      redirect_to root_url, info: 'Logged in!'
    rescue => e
      @error = e.message
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  private

  def permitted_params
    params.permit(:username, :password).to_h
  end

  def redis_params(response)
    token = response.dig('data', 'token').slice('access_token', 'token_type', 'expires_in', 'refresh_token')
    { 'email': permitted_params[:username] }.merge(token)
  end

  def create_params
    permitted_params.merge({ grant_type: 'password' })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :validate_password, only: [:create, :change_password]

  def show
    response = api_client.get_user(params[:id])
    @user = response.dig('data', 'user')
  end

  def create
    return if @error.present?

    begin
      response = api_client.create_user(user_params)
      User.create(redis_params(response))
      sign_in(permitted_params.slice(:email))
      redirect_to root_path, success: 'User is created and logged in successfully!'
    rescue => e
      @error = e.message
    end
  end

  def me
    response = api_client.my_profile
    @user = response.dig('data', 'user')
  end

  def update_profile
    begin
      response = api_client.change_password(user_params)
      User.create(redis_params(response))
      redirect_to me_users_path, success: 'User is updated successfully!'
    rescue => e
      @error = e.message
    end
  end

  def change_password
    return if @error.present?

    begin
      response = api_client.change_password(change_password_params)
      User.create(redis_params(response))
      redirect_to me_users_path, success: 'Password is updated successfully!'
    rescue => e
      @error = e.message
    end
  end

  def reset_password
    begin
      response = api_client.reset_password(reset_password_params)
      redirect_to root_path, success: response['message']
    rescue => e
      @error = e.message
    end
  end

  private

  def permitted_params
    params.permit(:email, :first_name, :last_name, :password, :current_password, :new_password, :date_of_birth).to_h
  end

  def validate_password
    password = params.has_key?(:password) ? params[:password] : params[:new_password]
    @error = "Password doesn't match" if password != params[:password_confirmation]
  end

  def change_password_params
    { user: permitted_params.slice(:current_password, :new_password) }
  end

  def reset_password_params
    { user: permitted_params.slice(:email) }
  end

  def redis_params(response)
    user = response.dig('data', 'user')&.slice('name', 'email', 'id') || default_params
    token = response.dig('data', 'token')&.slice('access_token', 'token_type', 'expires_in', 'refresh_token') || {}
    user.merge(token)
  end

  def user_params
    { user: permitted_params }
  end

  def default_params
    { email: current_user['email'] }
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def index
    visible_widgets = api_client.visible_widgets(search_term: params[:q])
    @widgets = visible_widgets.dig('data', 'widgets')
  end

  def all
  	user_widgets = api_client.user_widgets(search_term: params[:q])
    @widgets = user_widgets.dig('data', 'widgets')
  end

  def create
  	api_client.create_widget(widget_params)
  	redirect_to users_me_widgets_path, success: 'Widget created successfully!'
  rescue => e
    @error = e.message
  end

  def destroy
  	api_client.delete_widget(params[:id])
  	redirect_to users_me_widgets_path, success: 'Widget deleted successfully!'
  rescue => e
    redirect_to users_me_widgets_path, danger: e.message
  end

  private

  def permitted_params
    params.permit(:name, :description, :kind).to_h
  end

  def widget_params
    { widget: permitted_params }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users/widgets_helper.rb
module Users::WidgetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/_alert.html.haml
- flash.each do |type, message|
  .message{ class: "is-#{type}" }
    .message-body
      = message

- if message.present?
  .message.is-danger
    .message-body
      = message

app/views/layouts/_header.html.haml
%nav.navbar.is-fixed-top.is-light{"aria-label": "main navigation",  role: "navigation"}
  .navbar-brand
    %a.navbar-item{ href: root_path }
      %span.is-size-4.has-text-weight-bold WIDGETS
    %a.navbar-burger.burger{ "aria-expanded": "false", "aria-label": "menu", "data-target": "navbar-home",  role: "button" }
      %span{ "aria-hidden": "true" }
      %span{ "aria-hidden": "true" }
      %span{ "aria-hidden": "true" }
  #navbar-home.navbar-menu
    .navbar-start
      %a.navbar-item{ href: root_path }
        Home
      - if user_logged_in?
        %a.navbar-item{ href: users_me_widgets_path }
          My Widgets

    .navbar-end
      - unless user_logged_in?
        .navbar-item
          .buttons
            %a.button.is-small.is-primary.modal-trigger-button{ 'data-target': "signup-modal" }
              %strong Sign up
            %a.button.is-small.is-info.modal-trigger-button{ 'data-target': "login-modal" }
              %strong Log in
      - if user_logged_in?
        .navbar-item.has-dropdown.is-hoverable
          %a.navbar-link
            = current_user['name']
          .navbar-dropdown
            %a.navbar-item{ href: me_users_path }
              Manage Profile
            %a.navbar-item.modal-trigger-button{ 'data-target': "change-password-modal" }
              Change Password
            %hr.navbar-divider
            = link_to "Log out", session_path(current_user['id']), method: :delete, class: 'navbar-item'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type" }
    %title Widgets API
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body.has-navbar-fixed-top
    %nav.navbar.is-fixed-top.is-light{"aria-label": "main navigation",  role: "navigation"}
      .navbar-brand
        %a.navbar-item{ href: "/"}
          %span.is-size-4.has-text-weight-bold WIDGETS
        %a.navbar-burger.burger{ "aria-expanded": "false", "aria-label": "menu", "data-target": "navbar-home",  role: "button" }
          %span{ "aria-hidden": "true" }
          %span{ "aria-hidden": "true" }
          %span{ "aria-hidden": "true" }
      #navbar-home.navbar-menu
        .navbar-start
          %a.navbar-item
            Home
          %a.navbar-item
            Documentation
        .navbar-end
          .navbar-item
            .buttons
              %a.button.is-small.is-primary.modal-trigger-button{ 'data-target': "signup-modal" }
                %strong Sign up
              %a.button.is-small.is-info.modal-trigger-button{ 'data-target': "login-modal" }
                %strong Log in
          .navbar-item.has-dropdown.is-hoverable
            %a.navbar-link
              Jyothish Kumar
            .navbar-dropdown
              %a.navbar-item
                Manage Profile
              %a.navbar-item.modal-trigger-button{ 'data-target': "change-password-modal" }
                Change Password
              %hr.navbar-divider
              %a.navbar-item
                Logout

    %section.section
      .container
        = render 'layouts/alert'
        = render 'sessions/login'
        = render 'users/signup'
        = render 'users/change_password'
        = render 'users/reset_password'
        = yield

app/views/layouts/exception_layout.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type" }
    %title API Error
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %section.section
      .container
        = yield

app/views/layouts/no_network.html.haml
:css
  .box {
    height: 100vh;
    max-height: 300px;
    display: flex;
    justify-content: center;
    align-items: center;
  }

.box.has-text-centered.is-size-4.has-text-danger
  = @exception

app/views/users/_change_password.html.haml
#change-password-modal.modal
  .modal-background
  .modal-content
    .box
      .form-header-icon.has-text-centered
        %span
          %i.fa.fa-exclamation-circle.has-text-grey-lighter.fa-3x{ "aria-hidden" => "true" }

      #change-password-form-errors.level

      = form_tag(users_me_change_password_path, remote: true) do
        .field
          %p.control.has-icons-left
            %input.input.is-medium{ placeholder: "Current Password", type: "password", name: 'current_password' }
            %span.icon.is-small.is-left
              %i.fa.fa-lock
        .field
          %p.control.has-icons-left
            %input.input.is-medium{ placeholder: "New Password", type: "password", name: 'new_password' }
            %span.icon.is-small.is-left
              %i.fa.fa-lock
        .field
          %p.control.has-icons-left
            %input.input.is-medium{ placeholder: "Retype New Password", type: "password", name: 'password_confirmation'}
            %span.icon.is-small.is-left
              %i.fa.fa-lock
        .field
          %p.control.has-text-right
            = submit_tag "Change Password", class: "button is-danger is-medium"

  %button.modal-close.is-medium{ 'aria-label' => "close" }

app/views/users/_edit.html.haml
#edit-user-modal.modal
  .modal-background
  .modal-content
    .box
      .form-header-icon.has-text-centered
        %span
          %i.fa.fa-user-circle.has-text-grey-lighter.fa-3x{ 'aria-hidden' => 'true' }

      #edit-user-form-errors.level

      = form_tag(update_profile_users_path, method: :put, remote: true) do
        .field
          %p.control.has-icons-left.has-icons-right
            %input.input.is-medium{ placeholder: 'First Name', type: 'text', name: 'first_name', value: @user['first_name'], required: true }
            %span.icon.is-small.is-left
              %i.fa.fa-user
            %span.icon.is-small.is-right
              %i.fa.fa-check
        .field
          %p.control.has-icons-left.has-icons-right
            %input.input.is-medium{ placeholder: 'Last Name', type: 'text', name: 'last_name', value: @user['last_name'], required: true}
            %span.icon.is-small.is-left
              %i.fa.fa-user
            %span.icon.is-small.is-right
              %i.fa.fa-check
        .field
          %p.control.has-icons-left
            %input.input.is-medium{ placeholder: 'Date of birth', type: 'date', name: 'date_of_birth', value: @user['date_of_birth'], required: true }
            %span.icon.is-small.is-left
              %i.fa.fa-lock
        .field
          %p.control.has-text-right
            = submit_tag "Update", class: "button is-success is-medium"

  %button.modal-close.is-medium{ 'aria-label' => 'close' }

app/views/users/_reset_password.html.haml
#reset-password-modal.modal
  .modal-background
  .modal-content
    .box
      .form-header-icon.has-text-centered
        %span
          %i.fa.fa-exclamation-circle.has-text-grey-lighter.fa-3x{ "aria-hidden" => "true" }

      #reset-password-form-errors.level

      = form_tag(reset_password_users_path, remote: true) do
        .field
          %p.control.has-icons-left.has-icons-right
            %input.input.is-medium{ placeholder: "Email", type: "email", name: 'email' }
            %span.icon.is-small.is-left
              %i.fa.fa-envelope
            %span.icon.is-small.is-right
              %i.fa.fa-check
        .field
          %p.control.has-text-right
            = submit_tag "Reset Password", class: "button is-warning is-medium"

  %button.modal-close.is-medium{ 'aria-label' => "close" }

app/views/users/_signup.html.haml
#signup-modal.modal
  .modal-background
  .modal-content
    .box
      .form-header-icon.has-text-centered
        %span
          %i.fa.fa-user-circle.has-text-grey-lighter.fa-3x{ 'aria-hidden' => 'true' }

      #signup-form-errors.level

      = form_tag(users_path, remote: true) do
        .field
          %p.control.has-icons-left.has-icons-right
            %input.input.is-medium{ placeholder: 'Email', type: 'email', name: 'email', required: true }
            %span.icon.is-small.is-left
              %i.fa.fa-envelope
            %span.icon.is-small.is-right
              %i.fa.fa-check
        .field
          %p.control.has-icons-left.has-icons-right
            %input.input.is-medium{ placeholder: 'First Name', type: 'text', name: 'first_name', required: true }
            %span.icon.is-small.is-left
              %i.fa.fa-user
            %span.icon.is-small.is-right
              %i.fa.fa-check
        .field
          %p.control.has-icons-left.has-icons-right
            %input.input.is-medium{ placeholder: 'Last Name', type: 'text', name: 'last_name', required: true}
            %span.icon.is-small.is-left
              %i.fa.fa-user
            %span.icon.is-small.is-right
              %i.fa.fa-check
        .field
          %p.control.has-icons-left
            %input.input.is-medium{ placeholder: 'Password', type: 'password', name: 'password', required: true }
            %span.icon.is-small.is-left
              %i.fa.fa-lock
        .field
          %p.control.has-icons-left
            %input.input.is-medium{ placeholder: 'Retype Password', type: 'password', name: 'password_confirmation', required: true }
            %span.icon.is-small.is-left
              %i.fa.fa-lock
        .field
          %p.control.has-text-right
            = submit_tag "Sign Up", class: "button is-success is-medium"

  %button.modal-close.is-medium{ 'aria-label' => 'close' }

app/views/users/_user.html.haml
%table.table.is-fullwidth
  %tr
    %th ID
    %td= @user['id']
  %tr
    %th Name
    %td= @user['name']

  - if @user.has_key?('email')
    %tr
      %th Email
      %td= @user['email']
  %tr
    %th First Name
    %td= @user['first_name']
  %tr
    %th Last Name
    %td= @user['last_name']

  - if @user.has_key?('date_of_birth')
    %tr
      %th Date Of Birth
      %td= @user['date_of_birth']

  - if @user.has_key?('active')
    %tr
      %th Active?
      %td= @user['active'] ? 'Yes' : 'No'
  %tr
    %th Image
    %td
      %figure.image.is-64x64
        %img{ src: @user.dig('images', 'original_url') }

.level.has-text-right
  - if @user.has_key?('email')
    = render 'edit'
    %a.button.is-small.is-info.modal-trigger-button{ 'data-target': "edit-user-modal" }
      %strong Edit

app/views/users/change_password.js.erb
<% if @error.present? %>
  $('#change-password-form-errors').html("<%= j (render 'layouts/alert', message: @error) %>");
<% end %>

app/views/users/create.js.erb
<% if @error.present? %>
  $('#signup-form-errors').html("<%= j (render 'layouts/alert', message: @error) %>");
<% end %>

app/views/users/me.html.haml
.box
  .title.is-capitalized
    My Profile

  = render 'user'

app/views/users/reset_password.js.erb
<% if @error.present? %>
  $('#reset-password-form-errors').html("<%= j (render 'layouts/alert', message: @error) %>");
<% end %>

app/views/users/show.html.haml
.box
  .title.is-capitalized
    User Details

  = render 'user'

app/views/users/update_profile.js.erb
<% if @error.present? %>
  $('#edit-user-form-errors').html("<%= j (render 'layouts/alert', message: @error) %>");
<% end %>

app/views/widgets/_form.html.haml
#widget-form-modal.modal
  .modal-background
  .modal-content
    .box
      .form-header-icon.has-text-centered
        %span.is-size-5 Create Widget

      #widget-form-errors.level

      = form_tag(widgets_path, remote: true) do
        .field
          %p.control
            %input.input.is-medium{ placeholder: 'Name', type: 'text', name: 'name', required: true }
        .field
          %p.control
            %textarea.input.is-medium.textarea{ placeholder: 'Description', name: 'description', required: true }
        .field
          %p.control
            %label.radio
              %input{ name: "kind", type: "radio", value: 'visible', required: true }
              Visible
            %label.radio
              %input{ name: "kind", type: "radio", value: 'hidden', required: true }
              Hidden
        .field
          %p.control.has-text-right
            = submit_tag "Create", class: "button is-success is-medium"

  %button.modal-close.is-medium{ 'aria-label' => 'close' }

app/views/widgets/_widgets.html.haml
- destroyable = page == 'users'

%table.table.is-fullwidth.card
  %thead
    %tr
      %th ID
      %th Name
      %th Description
      %th Visible?
      - if destroyable
        %th
      - else
        %th User Name
  %tbody
    - if @widgets.blank?
      %tr
        %td{ colspan: 5 }
          .title.has-text-grey.has-text-centered
            No Widgets Found

    - @widgets.each do |widget|
      %tr
        %td=widget['id']
        %td=widget['name']
        %td=widget['description']
        %td=widget['kind'] == 'visible' ? 'YES' : 'NO'
        - if destroyable
          %td= link_to 'Delete', widget_path(widget['id']), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-danger'
        - else
          %td= link_to widget['user']['name'], user_path(widget['user']['id']), target: :_blank

app/views/widgets/all.html.haml
.level.has-text-right
  .level-left
    %a.button.is-small.is-warning.modal-trigger-button{ 'data-target': "widget-form-modal" }
      %strong Create Widget
    = render 'form'

  .level-right
    = form_tag("/users/me/widgets", method: 'get', remote: true) do
      .field.has-addons.level-item
        .control
          %input.input{ placeholder: "Type Widget Name", type: 'text', name: 'q' }
        .control
          = submit_tag "Search", class: "button is-warning"

#widgets-list
  = render 'widgets', page: 'users'

app/views/widgets/all.js.erb
$('#widgets-list').html("<%= j (render 'widgets', page: 'users') %>")

app/views/widgets/create.js.erb
<% if @error.present? %>
  $('#widget-form-errors').html("<%= j (render 'layouts/alert', message: @error) %>");
<% end %>

app/views/widgets/index.html.haml
.level.has-text-right
  .level-left
  .level-right
    = form_tag("/widgets", method: 'get', remote: true) do
      .field.has-addons.level-item
        .control
          %input.input{ placeholder: "Type Widget Name", type: 'text', name: 'q' }
        .control
          = submit_tag "Search", class: "button is-warning"

#widgets-list
  = render 'widgets', page: 'index'

app/views/widgets/index.js.erb
$('#widgets-list').html("<%= j (render 'widgets', page: 'index') %>")